import type { Metadata } from 'next'
import { Header } from '@/components/Header'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function AuthenticatedLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <div className="mb-10 flex w-full max-w-[1240px] flex-col">
      <Header />
      <div>{children}</div>
    </div>
  )
}
