'use client'

import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'

import './globals.css'
import { AuthContextProvider } from '@/contexts/AuthContext'

const epilogue = Epilogue({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="antialiased">
      <body className={epilogue.className + ' flex justify-center bg-dark-900'}>
        <AuthContextProvider>
          <div>{children}</div>
        </AuthContextProvider>
      </body>
    </html>
  )
}
