import type { Metadata } from 'next'
import { Epilogue } from 'next/font/google'
import { Header } from '@/components/Header'

import './globals.css'

const epilogue = Epilogue({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="antialiased">
      <body className={epilogue.className + ' flex justify-center bg-dark-900'}>
        <div className="mb-10 flex w-full max-w-[1240px] flex-col">
          <Header />
          <div>{children}</div>
        </div>
      </body>
    </html>
  )
}
